name: DS5111 su24 Python package 

on:
  push:
    branches:
      - WEEK-08/refactoring
  workflow_dispatch:

jobs:
  validate-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make update
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get texts
        run: |
          make get_texts

      - name: lint
        run: |
          make lint

      - name: Run non-integration tests
        
        run: |
          make test_non_integration
          
      - name: Run integration tests
        run: |
          make test_integration

      